apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-backend-depl
  labels:
    app: rest-backend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-backend-depl
  template:
    metadata:
      labels:
        app: rest-backend-depl
    spec:
      containers:
        - name: rest-backend
          image: rest-backend:0.0.1
          ports:
            - containerPort: 3128
          env:
            - name: REST_DB_USERNAME
              value: ariman
            - name: REST_DB_PASSWORD
              value: Password1
            - name: REST_DB_HOST
              value: mongodb-svc
            - name: REST_DB_PORT
              value: "27017"
            - name: REST_ENV
              value: containerized

---
apiVersion: v1
kind: Service
metadata:
  name: rest-backend-svc
spec:
  type: NodePort
  selector:
    app: rest-backend-depl
  ports:
    - protocol: TCP
      port: 3101
      targetPort: 3128
      nodePort: 32101
